<a href="https://colab.research.google.com/github/faheema2006/MLOPS/blob/main/Decision_Tree(Titanic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded=files.upload()

Saving titanic.csv to titanic.csv

In [4]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
inputs = df[['Pclass','Sex','Age','Fare']]
target = df['Survived']

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs

     Pclass     Sex   Age     Fare  female   male
0         3    male  22.0   7.2500   False   True
1         1  female  38.0  71.2833    True  False
2         3  female  26.0   7.9250    True  False
3         1  female  35.0  53.1000    True  False
4         3    male  35.0   8.0500   False   True
..      ...     ...   ...      ...     ...    ...
886       2    male  27.0  13.0000   False   True
887       1  female  19.0  30.0000    True  False
888       3  female   NaN  23.4500    True  False
889       1    male  26.0  30.0000   False   True
890       3    male  32.0   7.7500   False   True

[891 rows x 6 columns]

In [8]:
inputs = inputs.drop('Sex',axis='columns')
inputs

     Pclass   Age     Fare  female   male
0         3  22.0   7.2500   False   True
1         1  38.0  71.2833    True  False
2         3  26.0   7.9250    True  False
3         1  35.0  53.1000    True  False
4         3  35.0   8.0500   False   True
..      ...   ...      ...     ...    ...
886       2  27.0  13.0000   False   True
887       1  19.0  30.0000    True  False
888       3   NaN  23.4500    True  False
889       1  26.0  30.0000   False   True
890       3  32.0   7.7500   False   True

[891 rows x 5 columns]

In [9]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs

     Pclass        Age     Fare  female   male
0         3  22.000000   7.2500   False   True
1         1  38.000000  71.2833    True  False
2         3  26.000000   7.9250    True  False
3         1  35.000000  53.1000    True  False
4         3  35.000000   8.0500   False   True
..      ...        ...      ...     ...    ...
886       2  27.000000  13.0000   False   True
887       1  19.000000  30.0000    True  False
888       3  29.699118  23.4500    True  False
889       1  26.000000  30.0000   False   True
890       3  32.000000   7.7500   False   True

[891 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [12]:
from sklearn import tree

In [13]:
model = tree.DecisionTreeClassifier()

In [14]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [15]:
model.score(X_test,y_test)

0.7932960893854749

In [16]:
sample = pd.DataFrame([[3,22,7.25,1,0]],columns=inputs.columns)
prediction = model.predict(sample)
if prediction[0] == 1:
    print("Person Will Survive")
else:
    print("Person Will Not Survive")

Person Will Survive