<a href="https://colab.research.google.com/github/faheema2006/MLOPS/blob/main/SkillSync(One_Hot_Encoding).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving clean_resume_dataset.csv to clean_resume_dataset.csv

In [ ]:
import pandas as pd
df = pd.read_csv("clean_resume_dataset.csv")
df

,ResumeID,Category,Name,Email,Phone,Location,Summary,Skills,Experience,Education,Text,Source
0,REAL_0001,Java Developer,Chad Griffin,contact@email.com,94105 555 4321000 10 ...,"City, State",jessica claire montgomery street san francisco...,"Python, SQL, Git, Linux",jessica claire montgomery street san francisco...,Computer Science degree,jessica claire montgomery street san francisco...,ResumeAtlas
1,REAL_0002,Java Developer,Melinda Thomas,contact@email.com,17994568777 2017 2018 20152016 3 ...,"City, State",jared arthur maica java developer 17994568777 ...,"Python, SQL, Git, Linux",jared arthur maica java developer 17994568777 ...,Computer Science degree,jared arthur maica java developer 17994568777 ...,ResumeAtlas
2,REAL_0003,Java Developer,Shannon Mccarthy,contact@email.com,9 555 4321000 94105 8 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas
3,REAL_0004,Java Developer,Christine Kelley,contact@email.com,9 555 4321000 94105 5 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,ResumeAtlas
4,REAL_0005,Java Developer,Karen Holt,contact@email.com,100 10 4321000 ...,"City, State",jessica claire 100 montgomery st 10th floor xx...,"Python, SQL, Git, Linux",jessica claire 100 montgomery st 10th floor xx...,Computer Science degree,jessica claire 100 montgomery st 10th floor xx...,ResumeAtlas
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,SYNTH_3496,Technical Writer,Victor Green,victor.green@gmail.com,389.961.5738x5512,"Riveraville, DC",Dedicated Technical Writer with 9+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Principal Technical Writer at Apple (2022 - 20...,Bachelor of Science in Computer Science from S...,victor green email victor green gmail com phon...,Synthetic
3496,SYNTH_3497,Technical Writer,Jim Watson,jim.watson@hotmail.com,881.255.4260x9723,"West Kristin, NE",Dedicated Technical Writer with 7+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Technical Writer at Spotify (2021 - 2024): Imp...,Bachelor of Science in Information Systems fro...,jim watson jim watson hotmail com 881 255 4260...,Synthetic
3497,SYNTH_3498,Technical Writer,Katherine Kirby,katherine.kirby@yahoo.com,001-246-977-2051x71073,"West Patrickview, WV",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at GitHub (2021 - 2024):...,Bachelor of Engineering in Software Engineerin...,katherine kirby katherine kirby yahoo com 001...,Synthetic
3498,SYNTH_3499,Technical Writer,Denise Schmidt,denise.schmidt@hotmail.com,001-637-303-1754x38027,"Wesleymouth, VT",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Senior Technical Writer at Meta (2022 - 2024):...,Master of Engineering in Software Engineering ...,denise schmidt email denise schmidt hotmail co...,Synthetic
3499,SYNTH_3500,Technical Writer,Stephen White,stephen.white@gmail.com,(992)454-6862,"Wendymouth, MT",Dedicated Technical Writer with 8+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at Atlassian (2022 - 202...,Bachelor of Engineering in Computer Engineerin...,stephen white stephen white gmail com 992 454 ...,Synthetic

In [ ]:
dummies = pd.get_dummies(df['Category'])
dummies

,AI Engineer,Backend Developer,Blockchain,Blockchain Developer,Business Analyst,Cloud Engineer,Cybersecurity Analyst,Data Science,Database,Database Administrator,...,SAP Developer,SQL Developer,Site Reliability Engineer,Software Developer,System Administrator,Technical Lead,Technical Writer,Testing,UI/UX Designer,Web Designing
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
merged = pd.concat([df,dummies],axis='columns')
merged

,ResumeID,Category,Name,Email,Phone,Location,Summary,Skills,Experience,Education,...,SAP Developer,SQL Developer,Site Reliability Engineer,Software Developer,System Administrator,Technical Lead,Technical Writer,Testing,UI/UX Designer,Web Designing
0,REAL_0001,Java Developer,Chad Griffin,contact@email.com,94105 555 4321000 10 ...,"City, State",jessica claire montgomery street san francisco...,"Python, SQL, Git, Linux",jessica claire montgomery street san francisco...,Computer Science degree,...,False,False,False,False,False,False,False,False,False,False
1,REAL_0002,Java Developer,Melinda Thomas,contact@email.com,17994568777 2017 2018 20152016 3 ...,"City, State",jared arthur maica java developer 17994568777 ...,"Python, SQL, Git, Linux",jared arthur maica java developer 17994568777 ...,Computer Science degree,...,False,False,False,False,False,False,False,False,False,False
2,REAL_0003,Java Developer,Shannon Mccarthy,contact@email.com,9 555 4321000 94105 8 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,...,False,False,False,False,False,False,False,False,False,False
3,REAL_0004,Java Developer,Christine Kelley,contact@email.com,9 555 4321000 94105 5 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,...,False,False,False,False,False,False,False,False,False,False
4,REAL_0005,Java Developer,Karen Holt,contact@email.com,100 10 4321000 ...,"City, State",jessica claire 100 montgomery st 10th floor xx...,"Python, SQL, Git, Linux",jessica claire 100 montgomery st 10th floor xx...,Computer Science degree,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,SYNTH_3496,Technical Writer,Victor Green,victor.green@gmail.com,389.961.5738x5512,"Riveraville, DC",Dedicated Technical Writer with 9+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Principal Technical Writer at Apple (2022 - 20...,Bachelor of Science in Computer Science from S...,...,False,False,False,False,False,False,True,False,False,False
3496,SYNTH_3497,Technical Writer,Jim Watson,jim.watson@hotmail.com,881.255.4260x9723,"West Kristin, NE",Dedicated Technical Writer with 7+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Technical Writer at Spotify (2021 - 2024): Imp...,Bachelor of Science in Information Systems fro...,...,False,False,False,False,False,False,True,False,False,False
3497,SYNTH_3498,Technical Writer,Katherine Kirby,katherine.kirby@yahoo.com,001-246-977-2051x71073,"West Patrickview, WV",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at GitHub (2021 - 2024):...,Bachelor of Engineering in Software Engineerin...,...,False,False,False,False,False,False,True,False,False,False
3498,SYNTH_3499,Technical Writer,Denise Schmidt,denise.schmidt@hotmail.com,001-637-303-1754x38027,"Wesleymouth, VT",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Senior Technical Writer at Meta (2022 - 2024):...,Master of Engineering in Software Engineering ...,...,False,False,False,False,False,False,True,False,False,False
3499,SYNTH_3500,Technical Writer,Stephen White,stephen.white@gmail.com,(992)454-6862,"Wendymouth, MT",Dedicated Technical Writer with 8+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at Atlassian (2022 - 202...,Bachelor of Engineering in Computer Engineerin...,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
final = merged.drop(["Category","Data Science"],axis='columns')
final

,ResumeID,Name,Email,Phone,Location,Summary,Skills,Experience,Education,Text,...,SAP Developer,SQL Developer,Site Reliability Engineer,Software Developer,System Administrator,Technical Lead,Technical Writer,Testing,UI/UX Designer,Web Designing
0,REAL_0001,Chad Griffin,contact@email.com,94105 555 4321000 10 ...,"City, State",jessica claire montgomery street san francisco...,"Python, SQL, Git, Linux",jessica claire montgomery street san francisco...,Computer Science degree,jessica claire montgomery street san francisco...,...,False,False,False,False,False,False,False,False,False,False
1,REAL_0002,Melinda Thomas,contact@email.com,17994568777 2017 2018 20152016 3 ...,"City, State",jared arthur maica java developer 17994568777 ...,"Python, SQL, Git, Linux",jared arthur maica java developer 17994568777 ...,Computer Science degree,jared arthur maica java developer 17994568777 ...,...,False,False,False,False,False,False,False,False,False,False
2,REAL_0003,Shannon Mccarthy,contact@email.com,9 555 4321000 94105 8 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,...,False,False,False,False,False,False,False,False,False,False
3,REAL_0004,Christine Kelley,contact@email.com,9 555 4321000 94105 5 ...,"City, State",jessica claire 9 resumesampleexamplecom 555 43...,"Python, SQL, Git, Linux",jessica claire 9 resumesampleexamplecom 555 43...,Computer Science degree,jessica claire 9 resumesampleexamplecom 555 43...,...,False,False,False,False,False,False,False,False,False,False
4,REAL_0005,Karen Holt,contact@email.com,100 10 4321000 ...,"City, State",jessica claire 100 montgomery st 10th floor xx...,"Python, SQL, Git, Linux",jessica claire 100 montgomery st 10th floor xx...,Computer Science degree,jessica claire 100 montgomery st 10th floor xx...,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,SYNTH_3496,Victor Green,victor.green@gmail.com,389.961.5738x5512,"Riveraville, DC",Dedicated Technical Writer with 9+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Principal Technical Writer at Apple (2022 - 20...,Bachelor of Science in Computer Science from S...,victor green email victor green gmail com phon...,...,False,False,False,False,False,False,True,False,False,False
3496,SYNTH_3497,Jim Watson,jim.watson@hotmail.com,881.255.4260x9723,"West Kristin, NE",Dedicated Technical Writer with 7+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Technical Writer at Spotify (2021 - 2024): Imp...,Bachelor of Science in Information Systems fro...,jim watson jim watson hotmail com 881 255 4260...,...,False,False,False,False,False,False,True,False,False,False
3497,SYNTH_3498,Katherine Kirby,katherine.kirby@yahoo.com,001-246-977-2051x71073,"West Patrickview, WV",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at GitHub (2021 - 2024):...,Bachelor of Engineering in Software Engineerin...,katherine kirby katherine kirby yahoo com 001...,...,False,False,False,False,False,False,True,False,False,False
3498,SYNTH_3499,Denise Schmidt,denise.schmidt@hotmail.com,001-637-303-1754x38027,"Wesleymouth, VT",Dedicated Technical Writer with 6+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Senior Technical Writer at Meta (2022 - 2024):...,Master of Engineering in Software Engineering ...,denise schmidt email denise schmidt hotmail co...,...,False,False,False,False,False,False,True,False,False,False
3499,SYNTH_3500,Stephen White,stephen.white@gmail.com,(992)454-6862,"Wendymouth, MT",Dedicated Technical Writer with 8+ years of ex...,"Python, JavaScript, SQL, Git, Docker, AWS, Lin...",Lead Technical Writer at Atlassian (2022 - 202...,Bachelor of Engineering in Computer Engineerin...,stephen white stephen white gmail com 992 454 ...,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
print("Columns in 'final' DataFrame:")
print(final.columns.tolist())

Columns in 'final' DataFrame:
['ResumeID', 'Name', 'Email', 'Phone', 'Location', 'Summary', 'Skills', 'Experience', 'Education', 'Text', 'Source', 'AI Engineer', 'Backend Developer', 'Blockchain', 'Blockchain Developer', 'Business Analyst', 'Cloud Engineer', 'Cybersecurity Analyst', 'Database', 'Database Administrator', 'DevOps', 'Digital Media', 'DotNet Developer', 'ETL Developer', 'Engineering Manager', 'Frontend Developer', 'Full Stack Developer', 'Java Developer', 'Machine Learning Engineer', 'Mobile Developer', 'Network Security Engineer', 'Principal Engineer', 'Product Manager', 'Python Developer', 'QA Engineer', 'React Developer', 'SAP Developer', 'SQL Developer', 'Site Reliability Engineer', 'Software Developer', 'System Administrator', 'Technical Lead', 'Technical Writer', 'Testing', 'UI/UX Designer', 'Web Designing']

In [ ]:
print("Available columns in 'final' DataFrame:")
print(final.columns.tolist())

Available columns in 'final' DataFrame:
['ResumeID', 'Name', 'Email', 'Phone', 'Location', 'Summary', 'Skills', 'Experience', 'Education', 'Text', 'Source', 'AI Engineer', 'Backend Developer', 'Blockchain', 'Blockchain Developer', 'Business Analyst', 'Cloud Engineer', 'Cybersecurity Analyst', 'Database', 'Database Administrator', 'DevOps', 'Digital Media', 'DotNet Developer', 'ETL Developer', 'Engineering Manager', 'Frontend Developer', 'Full Stack Developer', 'Java Developer', 'Machine Learning Engineer', 'Mobile Developer', 'Network Security Engineer', 'Principal Engineer', 'Product Manager', 'Python Developer', 'QA Engineer', 'React Developer', 'SAP Developer', 'SQL Developer', 'Site Reliability Engineer', 'Software Developer', 'System Administrator', 'Technical Lead', 'Technical Writer', 'Testing', 'UI/UX Designer', 'Web Designing']

In [ ]:
columns_to_drop_for_X = ['ResumeID', 'Name', 'Email', 'Phone', 'Location', 'Summary', 'Skills', 'Experience', 'Education', 'Text', 'Source', 'AI Engineer']
X = final.drop(columns=columns_to_drop_for_X, axis=1)
y = final['AI Engineer']
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (3500, 34)
Shape of y: (3500,)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.score(X,y)

0.2467116272212595

In [ ]:
print(X.columns.tolist())

['Backend Developer', 'Blockchain', 'Blockchain Developer', 'Business Analyst', 'Cloud Engineer', 'Cybersecurity Analyst', 'Database', 'Database Administrator', 'DevOps', 'Digital Media', 'DotNet Developer', 'ETL Developer', 'Engineering Manager', 'Frontend Developer', 'Full Stack Developer', 'Java Developer', 'Machine Learning Engineer', 'Mobile Developer', 'Network Security Engineer', 'Principal Engineer', 'Product Manager', 'Python Developer', 'QA Engineer', 'React Developer', 'SAP Developer', 'SQL Developer', 'Site Reliability Engineer', 'Software Developer', 'System Administrator', 'Technical Lead', 'Technical Writer', 'Testing', 'UI/UX Designer', 'Web Designing']

In [ ]:

feature_columns = X.columns.tolist()
coefficients = model.coef_
intercept = model.intercept_
print(f"Model Intercept (baseline prediction with no other categories): {intercept:.4f}")
X_zero = np.zeros((1, len(feature_columns)))
prediction_zero_features = model.predict(X_zero)
print(f"Prediction for an AI Engineer (given NO other categories are present): {prediction_zero_features[0]:.2f}")
try:
    devops_index = feature_columns.index('DevOps')
    input_data_devops = [0] * len(feature_columns)
    input_data_devops[devops_index] = 1
    X_devops = np.array([input_data_devops])
    prediction_devops = model.predict(X_devops)
    print(f"Prediction for an AI Engineer (given ONLY 'DevOps' is present): {prediction_devops[0]:.2f}")
except ValueError:
    print("'DevOps' not found in feature columns. Please check the column name.")

Model Intercept (baseline prediction with no other categories): 0.2620
Prediction for an AI Engineer (given NO other categories are present): 0.26
Prediction for an AI Engineer (given ONLY 'DevOps' is present): -0.00

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(